const { calculateEphemeris } = require("./ephemeris-provider");
const SIGNS=["Mesha","Vrishabha","Mithuna","Karka","Simha","Kanya","Tula","Vrischika","Dhanu","Makara","Kumbha","Meena"];
const SIGN_EN=["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
const SIGN_LORD=["Mars","Venus","Mercury","Moon","Sun","Mercury","Venus","Mars","Jupiter","Saturn","Saturn","Jupiter"];
const NAK=["Ashwini","Bharani","Krittika","Rohini","Mrigashira","Ardra","Punarvasu","Pushya","Ashlesha","Magha","Purva Phalguni","Uttara Phalguni","Hasta","Chitra","Swati","Vishakha","Anuradha","Jyeshtha","Mula","Purva Ashadha","Uttara Ashadha","Shravana","Dhanishtha","Shatabhisha","Purva Bhadrapada","Uttara Bhadrapada","Revati"];
const LORDS=["Ketu","Venus","Sun","Moon","Mars","Rahu","Jupiter","Saturn","Mercury"];
const YEARS={Ketu:7,Venus:20,Sun:6,Moon:10,Mars:7,Rahu:18,Jupiter:16,Saturn:19,Mercury:17};
const PLANETS=["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn","Rahu","Ketu"];
const norm=x=>((Number(x)%360)+360)%360;
const sign=x=>Math.floor(norm(x)/30)+1;
const relHouse=(fromSign,toSign)=>((toSign-fromSign+12)%12)+1;
function nakshatra(longitude){const span=360/27,q=norm(longitude)/span,index=Math.min(26,Math.floor(q)),f=q-index;return{name:NAK[index],index:index+1,pada:Math.min(4,Math.floor(f*4)+1),lord:LORDS[index%9],degreesInNakshatra:+(f*13.3333333333).toFixed(6)}}
function houseFromAsc(asc,longitude){return relHouse(sign(asc),sign(longitude))}
function navamsaSign(longitude){const s=sign(longitude)-1,part=Math.min(8,Math.floor((norm(longitude)%30)/(30/9))),mod=s%3,start=mod===0?s:mod===1?(s+8)%12:(s+4)%12;return((start+part)%12)+1}
function buildD1(asc,planets){const lagna=sign(asc),d1=Array.from({length:12},(_,i)=>{const s=((lagna-1+i)%12)+1;return{house:i+1,sign:s,signName:SIGNS[s-1],signEnglish:SIGN_EN[s-1],planets:[]}});for(const p of PLANETS)d1[planets[p].house-1].planets.push(p);return d1}
function buildD9(asc,planets){const lagna=navamsaSign(asc),d9=Array.from({length:12},(_,i)=>{const s=((lagna-1+i)%12)+1;return{house:i+1,sign:s,signName:SIGNS[s-1],signEnglish:SIGN_EN[s-1],planets:[]}});for(const p of PLANETS){const ds=planets[p].d9Sign;const h=relHouse(lagna,ds);d9[h-1].planets.push(p)}return d9}
function addYears(date,years){return new Date(date.getTime()+Number(years)*365.2425*86400000)}
function parseBirthDateTime(input){const [y,m,d]=String(input.dob).split('-').map(Number);const [hh,mm,ss]=String(input.time||'12:00').split(':').map(Number);const off=Number(input.timezone??input.tzOffset??5.5);return new Date(Date.UTC(y,m-1,d,hh||0,mm||0,ss||0)-off*3600000)}
function generateSubPeriods(start,totalYears,parentLord){const result=[];let cursor=new Date(start),orderStart=LORDS.indexOf(parentLord);for(let j=0;j<9;j++){const lord=LORDS[(orderStart+j)%9],years=totalYears*YEARS[lord]/120,end=addYears(cursor,years);result.push({lord,start:cursor.toISOString().slice(0,10),end:end.toISOString().slice(0,10),years});cursor=end}return result}
function dashas(moonLongitude,input){const birth=parseBirthDateTime(input),n=nakshatra(moonLongitude),lord=n.lord,span=360/27,elapsed=(norm(moonLongitude)%span)/span,balance=YEARS[lord]*(1-elapsed),maha=[];let cursor=new Date(birth),index=LORDS.indexOf(lord);for(let i=0;i<18;i++){const md=LORDS[(index+i)%9],years=i===0?balance:YEARS[md],end=addYears(cursor,years),ad=generateSubPeriods(cursor,years,md),pd=ad.flatMap(a=>generateSubPeriods(new Date(a.start+"T00:00:00Z"),a.years,a.lord).map(x=>({...x,antardasha:a.lord})));maha.push({lord:md,start:cursor.toISOString().slice(0,10),end:end.toISOString().slice(0,10),years,balanceAtBirth:i===0,antardasha:ad,pratyantardasha:pd});cursor=end}return{birthDate:input.dob,birthTime:input.time,startingLord:lord,balanceYears:+balance.toFixed(8),mahadasha:maha}}
function lordOf(house,lagna){const s=((lagna-1+house-1)%12)+1;return SIGN_LORD[s-1]}
function occupiedHouse(planets,p){return planets[p]?.house||0}
function conjunction(planets,a,b){return planets[a].sign===planets[b].sign}
function kendraFrom(h1,h2){return [1,4,7,10].includes(relHouse(h1,h2))}
function aspectHouses(planet,from,to){const diff=relHouse(from,to);if(diff===7)return true;if(planet==='Mars'&&[4,8].includes(diff))return true;if(planet==='Jupiter'&&[5,9].includes(diff))return true;if(planet==='Saturn'&&[3,10].includes(diff))return true;return false}
function yogaRules(planets,lagna){const yogas=[],doshas=[],addY=(name,basis,strength='Rule match')=>yogas.push({name,basis,status:'Detected',strength}),addD=(name,basis,severity='Context dependent')=>doshas.push({name,basis,status:'Rule match',severity});
  if(conjunction(planets,'Sun','Mercury')) addY('Budhaditya Yoga','Sun and Mercury occupy the same sign. Classical strength depends on combustion, dignity and house context.');
  if(kendraFrom(planets.Moon.sign,planets.Jupiter.sign)) addY('Gajakesari Yoga','Jupiter is in a kendra (1/4/7/10) from the Moon.');
  if(conjunction(planets,'Moon','Mars')) addY('Chandra-Mangala Yoga','Moon and Mars occupy the same sign.');
  if(occupiedHouse(planets,'Mercury')===1||occupiedHouse(planets,'Mercury')===4||occupiedHouse(planets,'Mercury')===7||occupiedHouse(planets,'Mercury')===10){if([1,4,7,10].includes(planets.Mercury.house)&&[3,6].includes(planets.Mercury.sign%3+1)){} }
  const maha=[['Mars','Ruchaka', [1,4,7,10],[1,8]],['Mercury','Bhadra',[1,4,7,10],[3,6]],['Jupiter','Hamsa',[1,4,7,10],[4,9]],['Venus','Malavya',[1,4,7,10],[2,7]],['Saturn','Sasa',[1,4,7,10],[10,11]]];
  for(const [p,name,hs,ss] of maha) if(hs.includes(planets[p].house)&&ss.includes(planets[p].sign)) addY(name+' Mahapurusha Yoga',`${p} is in a kendra and in its own/exaltation sign under the configured Parashari screening rule.`);
  const ninth=lordOf(9,lagna),tenth=lordOf(10,lagna); if(planets[ninth]&&planets[tenth]&&(planets[ninth].sign===planets[tenth].sign||aspectHouses(ninth,planets[ninth].house,planets[tenth].house)||aspectHouses(tenth,planets[tenth].house,planets[ninth].house))) addY('Dharma-Karmadhipati Yoga',`9th lord ${ninth} and 10th lord ${tenth} are connected by conjunction/aspect under the configured rule.`);
  const second=lordOf(2,lagna),fifth=lordOf(5,lagna),ninthLord=lordOf(9,lagna); if([second,fifth,ninthLord].some(p=>planets[p]&&[1,2,5,9,11].includes(planets[p].house))) addY('Dhana Yoga Screening',`A wealth-house lord (2/5/9) occupies a configured wealth-supporting house.`);
  if([1,4,7,8,12].includes(planets.Mars.house)||[1,4,7,8,12].includes(relHouse(planets.Moon.sign,planets.Mars.sign))||[1,4,7,8,12].includes(relHouse(planets.Venus.sign,planets.Mars.sign))) addD('Mangal Dosha','Mars occupies a configured Manglik house from Lagna/Moon/Venus screening.','Cancellation and partner comparison required');
  if(conjunction(planets,'Sun','Rahu')||conjunction(planets,'Sun','Ketu')) addD('Surya Grahan Dosha','Sun is conjunct a lunar node.');
  if(conjunction(planets,'Moon','Rahu')||conjunction(planets,'Moon','Ketu')) addD('Chandra Grahan Dosha','Moon is conjunct a lunar node.');
  const malefics=['Sun','Mars','Saturn','Rahu','Ketu']; if(malefics.some(p=>conjunction(planets,'Moon',p))) addD('Papakartari/Chandra Affliction Screening','Moon is conjunct a configured natural malefic; full Papakartari requires adjacent-house checks.');
  if(planets.Mars.sign===4) addD('Mars Debilitation','Mars is in Cancer, its traditional debilitation sign.');
  if(planets.Saturn.sign===1) addD('Saturn Debilitation','Saturn is in Aries, its traditional debilitation sign.');
  if(planets.Jupiter.sign===10) addD('Jupiter Debilitation','Jupiter is in Capricorn, its traditional debilitation sign.');
  if(planets.Venus.sign===6) addD('Venus Debilitation','Venus is in Virgo, its traditional debilitation sign.');
  return{yogas,doshas,ruleSummary:{yogaRulesChecked:10,doshaRulesChecked:9}};
}
function makeUnsupportedVarga(name){return{supported:false,name,note:'Traditional Parashari/Jaimini rule set for this varga is not enabled yet.'}}
async function calculateKundli(input){const provider=await calculateEphemeris(input),asc=Number(provider.houses.ascendant),lagna=sign(asc),planets={};for(const p of PLANETS){const z=provider.planets[p],s=sign(z.longitude);planets[p]={name:p,longitude:+Number(z.longitude).toFixed(6),latitude:+Number(z.latitude||0).toFixed(6),speed:+Number(z.speed||0).toFixed(8),retrograde:Number(z.speed||0)<0,sign:s,signName:SIGNS[s-1],signEnglish:SIGN_EN[s-1],house:houseFromAsc(asc,z.longitude),nakshatra:nakshatra(z.longitude),d9Sign:navamsaSign(z.longitude)}}const d1=buildD1(asc,planets),d9=buildD9(asc,planets),charts={D1:d1,D9:d9};for(const n of ['D2','D3','D4','D5','D6','D7','D8','D10','D11','D12','D16','D20','D24','D27','D30','D40','D45','D60'])charts[n]=makeUnsupportedVarga(n);const rules=yogaRules(planets,lagna);return{input,ayanamsa:'Lahiri',lagna:{longitude:+asc.toFixed(6),sign:lagna,signName:SIGNS[lagna-1],signEnglish:SIGN_EN[lagna-1]},planets,charts,dasha:dashas(provider.planets.Moon.longitude,input),...rules,engine:{name:'Study Mantra Astrology Engine V9',provider:provider.provider|| (provider.fallback?'built-in-sidereal-astronomy':'local-swiss-ephemeris'),productionRequired:false,accuracyNote:'Sidereal Lahiri positions are calculated from the configured local ephemeris provider. The Vercel-safe fallback uses published astronomical orbital-element formulas; a local Swiss Ephemeris bridge can be used for higher-fidelity verification.'}}}
module.exports={calculateKundli,SIGNS,NAK,navamsaSign};
