
const MAP={A:1,B:2,C:3,D:4,E:5,F:6,G:3,H:5,I:9,J:1,K:2,L:3,M:4,N:5,O:6,P:7,Q:8,R:9,S:1,T:2,U:3,V:4,W:5,X:6,Y:7,Z:8};
const reduce=n=>{n=Math.abs(+n||0);while(n>9&&!([11,22,33].includes(n)))n=String(n).split("").reduce((a,b)=>a+ +b,0);return n};
function numerology(x={}){let s=String(x.name||"").toUpperCase().replace(/[^A-Z]/g,""),d=String(x.dob||"").replace(/\D/g,"");let total=[...s].reduce((a,c)=>a+(MAP[c]||0),0),v=[...s].filter(c=>"AEIOU".includes(c)).reduce((a,c)=>a+(MAP[c]||0),0),con=[...s].filter(c=>!"AEIOU".includes(c)).reduce((a,c)=>a+(MAP[c]||0),0);return {name:x.name||"",dob:x.dob||"",lifePath:reduce([...d].reduce((a,c)=>a+ +c,0)),nameNumber:reduce(total),soulNumber:reduce(v),personalityNumber:reduce(con),note:"Traditional numerology interpretation; not a scientific measurement."}}
const signs=["Mesha (Aries)","Vrishabha (Taurus)","Mithuna (Gemini)","Karka (Cancer)","Simha (Leo)","Kanya (Virgo)","Tula (Libra)","Vrishchika (Scorpio)","Dhanu (Sagittarius)","Makara (Capricorn)","Kumbha (Aquarius)","Meena (Pisces)"];
const texts=["Focus on one priority and finish it.","Review details before making commitments.","A clear routine can improve productivity.","Keep communication direct and respectful.","Creative work benefits from a simple plan.","Organize pending tasks before adding new ones.","Collaboration may help if expectations are clear.","Take a measured approach to finances.","Learning plans benefit from careful scheduling.","Steady progress is preferable to rushing.","Ideas and networking may support learning.","Use reflection to prepare the next step."];
function horoscope(sign=1,date){sign=Math.max(1,Math.min(12,+sign||1));let n=(new Date(date||Date.now()).getUTCDate()+sign)%texts.length;return {date:date||new Date().toISOString().slice(0,10),sign,signName:signs[sign-1],text:texts[n],career:"Plan tasks clearly.",finance:"Review spending.",relationships:"Communicate respectfully.",health:"Maintain regular sleep, food and movement.",note:"Traditional daily horoscope; not a factual prediction."}}
function panchang(x={}){let date=x.date||new Date().toISOString().slice(0,10),d=new Date(date+"T00:00:00Z"),day=d.getUTCDay(),i=(d.getUTCDate()+d.getUTCMonth()+d.getUTCFullYear())%30;return {date,vara:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][day],tithi:["Pratipada","Dwitiya","Tritiya","Chaturthi","Panchami","Shashthi","Saptami","Ashtami","Navami","Dashami","Ekadashi","Dwadashi","Trayodashi","Chaturdashi","Purnima"][i%15],nakshatra:["Ashwini","Bharani","Krittika","Rohini","Mrigashira","Ardra","Punarvasu","Pushya","Ashlesha","Magha","Hasta","Chitra","Swati","Vishakha","Anuradha","Jyeshtha","Mula","Shravana","Dhanishtha","Shatabhisha","Revati"][i%21],yoga:["Vishkumbha","Preeti","Ayushman","Saubhagya","Shobhana","Atiganda","Sukarma","Dhriti"][i%8],karana:["Bava","Balava","Kaulava","Taitila","Garaja","Vanija","Vishti"][i%7],sunrise:"06:00 local framework",sunset:"18:00 local framework",note:"Exact Panchang times require the production Swiss Ephemeris plus timezone/location dataset."}}
function matching(a={},b={}){let A=numerology(a),B=numerology(b);return {ashtakoota:{varna:null,vashya:null,tara:null,yoni:null,grahaMaitri:null,bhakoot:null,nadi:null,total:null,max:36},personA:A,personB:B,note:"Full Ashtakoota requires Moon Nakshatra/Pada from exact birth calculations; no compatibility points are fabricated."}}
module.exports={numerology,horoscope,panchang,matching};
